# Generated by Django 4.0.2 on 2022-04-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('NO', 'Normal'), ('FI', 'Fire'), ('WA', 'Water'), ('EL', 'Electric'), ('GR', 'Grass'), ('IC', 'Ice'), ('FG', 'Fighting'), ('PO', 'Poison'), ('GR', 'Ground'), ('FL', 'Flying'), ('PS', 'Psychic'), ('BU', 'Bug'), ('RO', 'Rock'), ('GH', 'Ghost'), ('DR', 'Dragon')], default='NO', max_length=2),
        ),
    ]
