# Generated by Django 4.0.2 on 2022-04-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_training'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='cat',
            new_name='pokemon',
        ),
    ]
