# Generated by Django 4.0.2 on 2022-04-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_cat_training_pokemon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('damage', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='attacks',
            field=models.ManyToManyField(to='main_app.Attack'),
        ),
    ]
